os: linux
language: android
dist: trusty
jdk: oraclejdk8

notifications:
  email:
    - ricardo.muhamed@gmail.com

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/daemon      #Cache daemon logs
    - $HOME/.gradle/native      #Cache library downloaded from the gradle dependency
    - $HOME/.gradle/wrapper     #Cache the gradle

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - build-tools-29.0.2
    - android-24
    - sys-img-armeabi-v7a-android-24

before_install:
  - yes | sdkmanager "platforms;android-29"
  - yes | sdkmanager "build-tools;28.0.3"

before_script:
    - echo "Launching Android emulator"
    - chmod +x gradlew
    - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
    - emulator -avd test -no-window &
    - android-wait-for-emulator
    - adb shell am broadcast -a android.intent.action.CLOSE_SYSTEM_DIALOGS
    - adb shell settings put global window_animation_scale 0 &
    - adb shell settings put global transition_animation_scale 0 &
    - adb shell settings put global animator_duration_scale 0 &
    - adb shell input keyevent 82 &
    - adb shell input keyevent 82 &

script:
    - echo "Starting build"
    - ./gradlew clean
    - ./gradlew testDebug


after_success:
    - bash <(curl -s https://codecov.io/bash)
