language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools

    - build-tools-29.0.2

    - android-29

before_install:
  - yes | sdkmanager "platforms;android-29"
  - yes | sdkmanager "build-tools;28.0.3"


script:
    - ./gradlew clean assembleDebug testDebug