codecov:
  ci:
    - travis.org

coverage:
  precision: 2
  round: down
  range: "75...100"

  status:
    project:
      unit:
        target: 75%
        threshold: 1%
        flag: unit
        flags:
          - unit

    patch:
      unit:
        target: 0
        flag: unit
        flags:
          - unit

    changes:
      unit:
        target: 0
        flag: unit
        flags:
          - unit